name: diff_match_patch
version: 0.4.1
description: The Diff Match and Patch libraries offer robust algorithms to perform the operations required for synchronizing plain text.
repository: https://github.com/espresso3389/diff-match-patch

environment:
  sdk: ">=3.9.0 <4.0.0"

dev_dependencies:
  test: any
  lints: ^5.0.0
  